### ISSUE TITLE
Website prints to javascript console

### ISSUE THREAD

**Issue by pblumenkamp** [ag-computational-bio/bakta-web-ui#1]
![image](https://user-images.githubusercontent.com/9703726/123398058-67a23000-d5a3-11eb-9835-7aa7ce774fc4.png)

"x" gets printed once when the page opened, "parsing file" every time a file was uploaded.

**Comment by pblumenkamp** [comment]
![image](https://user-images.githubusercontent.com/9703726/123400819-73dbbc80-d5a6-11eb-97a8-e05e56faaa70.png)

After opening the results page

**Comment by lukasjelonek** [comment]
Removed
