### ISSUE TITLE
Orphan jobs are not locally discarded

### ISSUE THREAD

**Issue by oschwengers** [ag-computational-bio/bakta-web-ui#13]
Orphan jobs should be automatically discarded if not available anymore on the server side.

Instead we get this note "server did not provide information for this job":

![image](https://user-images.githubusercontent.com/10071818/159508556-9992560a-e6b5-4818-8688-b824eff63eea.png)

**Comment by St4NNi** [comment]
This will be fixed in the next version of the backend. The server will correctly report a `NOT_FOUND` status for missing jobs as well as a properly functioning delete method for jobs.

**Comment by lukasjelonek** [comment]
Is the server part fixed? Does the UI now behave as required/expected?

**Comment by oschwengers** [comment]
Yes it does.
