### ISSUE TITLE
Error for genome annotation

### ISSUE THREAD

**Issue by fran1722** [ag-computational-bio/bakta-web-ui#18]
Everytime I upload my fasta files for annotation, it takes some seconds and immediately appears as error. I thought it was an issue from my fasta file but I tried with other files I previously uploaded on Bakta and I had the same result.

**Comment by St4NNi** [comment]
Hi, thanks for reporting! We had an issue with our backend infrastructure that should be fixed by now.
Unfortunately, this has resulted in a very long queue. We are currently working on processing this queue as quickly as possible, but it may take a while.
