### ISSUE TITLE
Bakta web version ignores translation table change

### ISSUE THREAD

**Issue by oschwengers** [ag-computational-bio/bakta-web-ui#19]
Originally reported by @AggressiveHayBale in https://github.com/oschwengers/bakta/issues/305

**Description**
Accessing the current version of web version of Bakta (Software: 1.9.1| DB: 5.0.0)  and selecting Translational table: 4: The Mold... results in the Bakta execution on the default table 11, ignoring the selection. 

**Step to replicate**
Annotate the genome while changing the translational table 11 to 4. 

**Output**
The output json reports:

```
{
    "genome": {
        "genus": null,
        "species": null,
        "strain": null,
        "complete": true,
        "gram": "?",
        "translation_table": 11
    }
```

I assume somewhere in the web version code either referring to this parameter is overwritten or the selection in the web GUI goes nowhere (I couldn't find the code related to the web code in the repo).

**Comment by St4NNi** [comment]
This will be fixed by the new [backend branch](https://github.com/ag-computational-bio/bakta-web-backend/tree/feat/backend_rework)

**Comment by oschwengers** [comment]
OK, this is live and fixed. Thanks!
