### ISSUE TITLE
Job submissions stuck

### ISSUE THREAD

**Issue by MariusDieckmann** [ag-computational-bio/bakta-web-ui#2]
Job submission in UI ist stuck after the following input:
\>a
a

**Comment by lukasjelonek** [comment]
As fasta file or via sequence entry field?

**Comment by oschwengers** [comment]
in this particular case is was a Fasta file. But it should work (and be tested) via the sequence field, as well.

**Comment by lukasjelonek** [comment]
Fixed. Please check if it behaves as expected.
