### ISSUE TITLE
"NoSuchKey" error on GFF3 download

### ISSUE THREAD

**Issue by oschwengers** [ag-computational-bio/bakta-web-ui#21]
When downloading the `.gff3` result file of a successful annotation, the following error appears:

![image](https://github.com/user-attachments/assets/8c3ac08e-0f97-450d-b339-907b9b0c142f)

Initially reported by a user via email.

**Comment by St4NNi** [comment]
Fixed by https://github.com/ag-computational-bio/bakta-web-backend/commit/926a99f0c246c34816053750b4b839ad78fda54f
