### ISSUE TITLE
Uncatched error when uploading wrong file

### ISSUE THREAD

**Issue by pblumenkamp** [ag-computational-bio/bakta-web-ui#3]
When uploading a wrong file, there is only an error message on the javascript console. 

![image](https://user-images.githubusercontent.com/9703726/123403186-cfa74500-d5a8-11eb-8540-5d96508e8a94.png)

**Comment by lukasjelonek** [comment]
Is fixed. Please check if the error disappeared.

**Comment by pblumenkamp** [comment]
Fixed :+1:
