### ISSUE TITLE
Topology and Type drop-down menu is not reset correctly

### ISSUE THREAD

**Issue by jhahnfeld** [ag-computational-bio/bakta-web-ui#4]
Checking "Complete genome" in Annotation will set all Topology entries in Replicons to "circular" and Type entries to "Chromosome".
After unchecking "Complete Genome", the entries will not be reset to the default value Topology: linear and Type: Contig.

**Comment by lukasjelonek** [comment]
Updated. Please check if it works as expected.

**Comment by jhahnfeld** [comment]
Unchecking "Complete genome" now correctly resets the Topology and Type entries.
