### ISSUE TITLE
Software / DB version

### ISSUE THREAD

**Issue by oschwengers** [ag-computational-bio/bakta-web-ui#6]
Currently the software and db version is given as `(Bakta-Version: 1.0.0| BaktaDB-Version: 2.0.0)`

Maybe this could be clipped to `(Software: 1.0.0 | DB: 2.0.0)`

**Comment by lukasjelonek** [comment]
Is changed, see 24c7e4e4d7826ab61ec28c5d35ad6c43aa292370
